# Generated by Django 5.1.1 on 2024-10-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_certificate_profileuser_delete_profilecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
