# Generated by Django 5.1.1 on 2024-10-08 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_lesson_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lessonvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
