# Generated by Django 5.1.1 on 2024-10-20 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_module_options_alter_module_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(blank=True, choices=[('any', 'Anyone'), ('email', 'Email required')], default='email', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_courses', through='courses.Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, choices=[('publish', 'Published'), ('soon', 'Coming Soon'), ('draft', 'Draft')], default='draft', max_length=10, null=True),
        ),
    ]
