# Generated by Django 5.1.1 on 2024-10-20 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', through='courses.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
