# Generated by Django 5.1.1 on 2024-10-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True),
        ),
    ]
