# Generated by Django 5.1.1 on 2024-10-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_notification'),
        ('instructors', '0002_instructor_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_instructure', to='instructors.instructor'),
        ),
    ]
