# Generated by Django 5.1.1 on 2024-10-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('in_progress', 'In Progress'), ('rejected', 'Rejected')], default='abandoned'),
        ),
    ]
