# Generated by Django 5.1.2 on 2024-10-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True),
        ),
    ]
