# Generated by Django 5.1.2 on 2024-10-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_notification_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True),
        ),
    ]
